version: "3.9"

services:

  frontend:
    container_name: feedback-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      PORT: 3000
      REACT_APP_API_URL: http://localhost:3333
    ports:
      - 3000:3000
    depends_on:
      - api
    volumes:
      - ./frontend:/home/node/app

  api:
    container_name: feedback-api
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      PORT: 3333
      MONGODB_URI: mongodb://feedback-db:27017/feedback
    ports:
      - 3333:3333
    depends_on:
      - db
    volumes:
      - ./api:/home/node/app

  db:
    image: mongo
    container_name: feedback-db
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
